#!/bin/bash

echo "=== FORCE REBUILD TERMINAL FUZZ v4.00 ==="
echo "1. Cleaned old plugin cache"
echo "2. Cleaned build directory" 
echo "3. Source code verified with Q1 signal chain and uniform VBE scaling"
echo ""
echo "*** MANUAL BUILD REQUIRED ***"
echo "In Xcode:"
echo "1. Product → Clean Build Folder"
echo "2. Build both AU and VST3 targets"
echo "3. Check plugins are installed in:"
echo "   - /Users/williamsmith/Library/Audio/Plug-Ins/Components/"
echo "   - /Users/williamsmith/Library/Audio/Plug-Ins/VST3/"
echo ""
echo "Expected version: v4.00-COMPLETE-3BJT-CIRCUIT"
echo "Expected signal chain: Input → Q2 → Q3 → Q1 → Output"
echo "Expected VBE scaling: uniform (0.002f for all transistors)"
echo ""
echo "Cache cleared. Ready for clean build!"